using System.Collections.Generic;

namespace SharpIpp.Protocol.Models
{
    public static class JobAttribute
    {
        public const string Compression = "compression";
        public const string Copies = "copies";
        public const string DateTimeAtCompleted = "date-time-at-completed";
        public const string DateTimeAtCreation = "date-time-at-creation";
        public const string DateTimeAtProcessing = "date-time-at-processing";
        public const string DocumentFormat = "document-format";
        public const string DocumentName = "document-name";
        public const string Finishings = "finishings";
        public const string IppAttributeFidelity = "ipp-attribute-fidelity";
        public const string JobUri = "job-uri";
        public const string JobId = "job-id";
        public const string JobImpressions = "job-impressions";
        public const string JobImpressionsCompleted = "job-impressions-completed";
        public const string JobKOctets = "job-k-octets";
        public const string JobKOctetsProcessed = "job-k-octets-processed";
        public const string JobMediaSheets = "job-media-sheets";
        public const string JobMediaSheetsCompleted = "job-media-sheets-completed";
        public const string JobName = "job-name";
        public const string JobOriginatingUserName = "job-originating-user-name";
        public const string JobPrinterUpTime = "job-printer-up-time";
        public const string JobPrinterUri = "job-printer-uri";
        public const string JobSheets = "job-sheets";
        public const string JobState = "job-state";
        public const string JobStateMessage = "job-state-message";
        public const string JobStateReasons = "job-state-reasons";
        public const string Media = "media";
        public const string MultipleDocumentHandling = "multiple-document-handling";
        public const string NumberUp = "number-up";
        public const string OrientationRequested = "orientation-requested";
        public const string PrinterResolution = "printer-resolution";
        public const string PrintQuality = "print-quality";
        public const string Sides = "sides";
        public const string TimeAtCompleted = "time-at-completed";
        public const string TimeAtCreation = "time-at-creation";
        public const string TimeAtProcessing = "time-at-processing";
        public const string NumberOfInterveningJobs = "number-of-intervening-jobs";
        public const string JobPriority = "job-priority";
        public const string JobHoldUntil = "job-hold-until";
        public const string PageRanges = "page-ranges";
        public const string PrintScaling = "print-scaling";
        public const string RequestingUserName = "requesting-user-name";
        public const string AttributesCharset = "attributes-charset";
        public const string AttributesNaturalLanguage = "attributes-natural-language";
        public const string DocumentNaturalLanguage = "document-natural-language";
        public const string FirstPrinterName = "first-printer-name";
        public const string PrinterId = "printer-id";
        public const string PrinterLocation = "printer-location";
        public const string PrinterType = "printer-type";
        public const string PrinterTypeMask = "printer-type-mask";
        public const string RequestedAttributes = "requested-attributes";
        public const string Limit = "limit";
        public const string WhichJobs = "which-jobs";
        public const string MyJobs = "my-jobs";
        public const string PrinterUri = "printer-uri";
        public const string DocumentUri = "document-uri";
        public const string LastDocument = "last-document";
        public const string PrintColorMode = "print-color-mode";
        public const string Message = "message";
        public const string StatusMessage = "status-message";
        public const string DetailedStatusMessage = "detailed-status-message";
        public const string JobDetailedStatusMessages = "job-detailed-status-messages";
        public const string JobDocumentAccessErrors = "job-document-access-errors";
        public const string JobMessageFromOperator = "job-message-from-operator";
        public const string JobMoreInfo = "job-more-info";
        public const string NumberOfDocuments = "number-of-documents";
        public const string OutputDeviceAssigned = "output-device-assigned";
        

        public static IEnumerable<string> GetAttributes( IppVersion version )
        {
            yield return Compression;
            yield return Copies;
            yield return DateTimeAtCompleted;
            yield return DateTimeAtCreation;
            yield return DateTimeAtProcessing;
            yield return DocumentFormat;
            yield return DocumentName;
            yield return Finishings;
            yield return IppAttributeFidelity;
            yield return JobUri;
            yield return JobId;
            yield return JobImpressions;
            yield return JobImpressionsCompleted;
            yield return JobKOctetsProcessed;
            yield return JobMediaSheets;
            yield return JobMediaSheetsCompleted;
            yield return JobName;
            yield return JobOriginatingUserName;
            yield return JobPrinterUpTime;
            yield return JobPrinterUri;
            yield return JobSheets;
            yield return JobState;
            yield return Media;
            yield return MultipleDocumentHandling;
            yield return NumberUp;
            yield return OrientationRequested;
            yield return PrinterResolution;
            yield return PrintQuality;
            yield return Sides;
            yield return TimeAtCompleted;
            yield return TimeAtCreation;
            yield return TimeAtProcessing;
            yield return NumberOfInterveningJobs;
            yield return JobPriority;
            yield return JobHoldUntil;
            yield return PageRanges;
            yield return PrintScaling;
            yield return RequestingUserName;
            yield return AttributesCharset;
            yield return AttributesNaturalLanguage;
            yield return DocumentNaturalLanguage;
            yield return FirstPrinterName;
            yield return PrinterId;
            yield return PrinterLocation;
            yield return PrinterType;
            yield return PrinterTypeMask;
            yield return RequestedAttributes;
            yield return Limit;
            yield return WhichJobs;
            yield return MyJobs;
            yield return PrinterUri;
            yield return DocumentUri;
            yield return LastDocument;
            yield return PrintColorMode;
            yield return Message;
        }
    }
}
