name: Publish docfx to Pages

on:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install docfx
      run: dotnet tool install -g docfx

    - name: Build docfx page
      run: docfx docfx/docfx.json

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docfx/_site

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
